#ifndef MAIN
#define MAIN
int _putchar(char c);
int main(void);
void reset_to_98(int *n);
int main(void);
void swap_int(int *a, int *b);
int main(void);
int _strlen(char *s);
int main(void);
void _puts(char *str);
int main(void);
void print_rev(char *s);
int main(void);
void rev_string(char *s);
int main(void);
void puts2(char *str);
int main(void);
void puts_half(char *str);
int main(void);
void print_array(int *a, int n);
int main(void);
char *_strcpy(char *dest, char *src);
int main(void);
int _atoi(char *s);
int main(void);
char *_strcat(char *dest, char *src);
int main(void);
char *_strncat(char *dest, char *src, int n);
int main(void);
char *_strncpy(char *dest, char *src, int n);
int main(void);
int _strcmp(char *s1, char *s2);
int main(void);
void reverse_array(int *a, int n);
int main(void);
char *string_toupper(char *);
int main(void);
char *cap_string(char *);
int main(void);
char *leet(char *);
#endif
