#ifndef MAIN
#define MAIN
int _putchar(char c);
int main(void);
void reset_to_98(int *n);
int main(void);
void swap_int(int *a, int *b);
int main(void);
int _strlen(char *s);
int main(void);
void _puts(char *str);
int main(void);
void print_rev(char *s);
int main(void);
void rev_string(char *s);
int main(void);
void puts2(char *str);
int main(void);
void puts_half(char *str);
int main(void);
void print_array(int *a, int n);
int main(void);
char *_strcpy(char *dest, char *src);
int main(void);
int _atoi(char *s);
int main(void);
char *_strcat(char *dest, char *src);
int main(void);
char *_strncat(char *dest, char *src, int n);
int main(void);
char *_strncpy(char *dest, char *src, int n);
int main(void);
int _strcmp(char *s1, char *s2);
int main(void);
void reverse_array(int *a, int n);
int main(void);
char *string_toupper(char *);
int main(void);
char *cap_string(char *);
int main(void);
char *leet(char *);
int main(void);
void simple_print_buffer(char *buffer, unsigned int size);
char *_memset(char *s, char b, unsigned int n);
void simple_print_buffer(char *buffer, unsigned int size);
int main(void);
char *_memcpy(char *dest, char *src, unsigned int n);
int main(void);
char *_strchr(char *s, char c);
int main(void);
unsigned int _strspn(char *s, char *accept);
int main(void);
char *_strpbrk(char *s, char *accept);
int main(void);
char *_strstr(char *haystack, char *needle);
int main(void);
void print_chessboard(char (*a)[8]);
int main(void);
void print_diagsums(int *a, int size);
#endif
